# Generated by Django 2.2.7 on 2019-11-13 01:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='casino_logos/', verbose_name='Suplier image')),
                ('ca_license_bool', models.BooleanField(default=False, max_length=100, verbose_name='License Y/N')),
                ('suplier_type', models.IntegerField(choices=[(0, 'Casino'), (1, 'Betting'), (2, 'CS:GO'), (3, 'Other')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_word_desc', models.CharField(max_length=300, verbose_name='About the bonus in 2 words')),
                ('bonus_digit', models.PositiveSmallIntegerField(verbose_name='Bonus value')),
                ('bonus_desc', models.TextField(blank=True, verbose_name='Bonus description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bonus_images/', verbose_name='Bonus image')),
                ('dep_bool', models.BooleanField(default=True)),
                ('dep', models.PositiveSmallIntegerField()),
                ('doa', models.DateField(default=datetime.date.today)),
                ('ttl', models.SmallIntegerField(blank=True, default=7, null=True, verbose_name='Amount of days to bonus expiring')),
                ('wager', models.SmallIntegerField(blank=True, default=0, verbose_name='Bonus wager')),
                ('bonus_type', models.IntegerField(choices=[(0, 'Deposit'), (1, 'Freespin')], default=0)),
                ('suplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestbonus.Suplier')),
            ],
            options={
                'ordering': ['-bonus_digit'],
            },
        ),
    ]
