# Generated by Django 2.2.7 on 2019-11-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestbonus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplier',
            name='ca_license_bool',
            field=models.BooleanField(default=False, verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='suplier_type',
            field=models.IntegerField(choices=[(0, 'Casino'), (1, 'Betting'), (2, 'CS:GO')], default=0),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
