# Generated by Django 2.2.7 on 2019-11-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestbonus', '0002_auto_20191130_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='doe',
            field=models.DateField(blank=True, null=True, verbose_name='Date of expiring'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='bonus_desc',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Bonus description'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='bonus_digit',
            field=models.PositiveSmallIntegerField(default=0, max_length=20, verbose_name='Bonus value'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='wager',
            field=models.SmallIntegerField(blank=True, default=0, max_length=3, verbose_name='Bonus wager'),
        ),
    ]
