# Generated by Django 2.2.7 on 2019-11-30 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestbonus', '0003_auto_20191130_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='bonus_digit',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000)], verbose_name='Bonus value'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='wager',
            field=models.SmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Bonus wager'),
        ),
    ]
