# Generated by Django 2.2.7 on 2019-12-01 02:17

import bestbonus.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestbonus', '0004_auto_20191130_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='ttl',
        ),
        migrations.AlterField(
            model_name='bonus',
            name='doa',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of adding'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='doe',
            field=models.DateField(default=bestbonus.models.today_plus_30_days, verbose_name='Date of expiring'),
        ),
    ]
